audit_header: false
title: Miami Real Estate Video Blog with Jorge Gonzalez
description: Our mission at Team Dad of Eight is to be your best resource for Miami real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Team Dad of Eight, your professional Miami Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jorge Gonzalez
  title:
  license_number:
  about_markdown: |
    Jorge Gonzalez and his “Team Dad of Eight" will help you sell your home in a way that accomplishes your personal and financial goals by making the best use of technology to create massive market exposure and secure the highest price and best terms for the sale of your home in the shortest possible time.

    Jorge has been selling, managing and investing in both residential and commercial real estate since 1986 and has worked with Buyers and Sellers to navigate them through hundreds of transactions. Jorge's education and proven experience have earned him the distinguished CRS Designation - "Certified Residential Specialist" - which is achieved by only 3% of all Realtors in the country.
  brand: Team Dad of Eight
  brokerage: Keller Williams
  market: Miami
  address: 11420 N. Kendall Dr., Suite 207, Miami, FL 33176
  phone: 305-239-8939
  phone_type: Office
  phone2: 305-898-6224
  phone2_type: Cell
  email: Jorge@DadOf8RealEstate.com
  url: http://dadof8realestate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Miami Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Miami Home?"
    CTA_text2: "Search the entire MLS for your Miami home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pg/TeamDadOf8
  linkedin_url: https://www.linkedin.com/in/jorgedadof8/
  youtube_url: https://www.youtube.com/channel/UCdCOpdxGc3LFv88vRlfeXQQ/videos
  twitter_url: https://twitter.com/TeamDadOf8
  instagram_url: https://www.instagram.com/teamdadof8/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Miami Real Estate Podcast with Jorge Gonzalez'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Miami Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Team Dad of Eight - your professional Miami Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Miami, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jorge Gonzalez'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Miami Real Estate Video Blog
  hero_background_hex: '#ffffff'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#ce123f'
  theme_color: '#003e7e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
